### ISSUE TITLE
Device ID (Not able to enter any information)

### ISSUE THREAD

**Issue by wnaylor** [catduckgnaf/ryobi_gdo#66]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

When I go to install the integration, after entering my username and password and submitting I get a box to enter my Device ID but nowhere in the box is a place to enter the ID.

### Describe the solution you'd like

None

### Describe alternatives you've considered

None

### Additional context

This is for an issue not a request for an issue
<img width="455" alt="Screenshot 2024-03-24 at 1 00 43 PM" src="https://github.com/catduckgnaf/ryobi_gdo/assets/4623959/ae228b70-d397-40cc-a35b-b77ae97e03ba">

**Comment by catduckgnaf** [comment]
Have you registered with the ryobi app? and are you able to login there and see the device?

**Comment by wnaylor** [comment]
I figured it out I was using the wrong username and password. When I entered the correct ones the device id was there and all I had to do was check it and submit it.

**Comment by catduckgnaf** [comment]
Closing, issue was user error, :)
